data:
  data_keys: ['metr-la', 'pems-bay', 'seattle']
  metr-la:
    dataset_path: data/metr-la/dataset.npy
    adjacency_matrix_path: data/metr-la/matrix.npy
    time_step: 34272
    node_num: 207
    speed_mean: 58.465786
    speed_std: 12.905341
  
  pems-bay:
    dataset_path: data/pems-bay/dataset.npy
    adjacency_matrix_path: data/pems-bay/matrix.npy
    time_step: 52116
    node_num: 325
    speed_mean: 62.621582859
    speed_std: 9.58811369696

  chengdu_m:
    dataset_path: data/chengdu_m/dataset.npy
    adjacency_matrix_path: data/chengdu_m/matrix.npy
    time_step: 17280
    node_num: 524
    speed_mean: 29.0982979559
    speed_std: 9.75304346669
  
  shenzhen:
    dataset_path: data/shenzhen/dataset.npy
    adjacency_matrix_path: data/shenzhen/matrix.npy
    time_step: 17280
    node_num: 627
    speed_mean: 30.5735608506
    speed_std: 11.0922606598

  seattle:
    dataset_path: data/seattle/dataset.npy
    adjacency_matrix_path: data/seattle/matrix.npy
    time_step: 105120
    node_num: 323
    speed_mean: 56.5738403483
    speed_std: 12.7362446890